apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-json
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-json
  template:
    metadata:
      labels:
        app: echo-json
    spec:
      containers:
      - name: echo-json
        image: rossmcd/echo-json:latest
        ports:
        - containerPort: 8889
---
apiVersion: v1
kind: Service
metadata:
  name: echo-json
  labels:
    app: echo-json
spec:
  ports:
  - port: 8889
    targetPort: 8889
    protocol: TCP
    name: http
  selector:
    app: echo-json
---
apiVersion: v1
kind: Service
metadata:
  name: echo-json-lb
  labels:
    app: echo-json
spec:
  type: LoadBalancer
  ports:
  - port: 8889
    targetPort: 8889
    protocol: TCP
    name: http
  selector:
    app: echo-json
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echo-json
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - http:
      paths:
      - path: /echo
        backend:
          serviceName: echo-json
          servicePort: 8889
